### ISSUE TITLE
JobObject.SetLimits fails if CpuRate is not set

### ISSUE THREAD

**Issue by m-mertz** [williamb1024/fs-processes#1]
Repro:
```csharp
using (var jobObject = new JobObject())
{
    var jobLimits = new JobLimits();
    jobLimits.Options = JobOptions.TerminateProcessesWhenJobClosed;
    jobLimits.ActiveProcesses = 1;
    jobObject.SetLimits(jobLimits);
}
```

Output:
```
Unhandled Exception:
System.ComponentModel.Win32Exception (0x80004005): The parameter is incorrect
   at Fs.Processes.JobObjects.JobObject.SetLimits(JobLimits& newLimits)
```

Cause:

Looks like SetInformationJobObject fails if JOBOBJECT_CPU_RATE_CONTROL_INFORMATION.ControlFlags or .CpuRate is 0, which is the default value for both. [This doc](https://docs.microsoft.com/en-us/windows/desktop/api/winnt/ns-winnt-_jobobject_cpu_rate_control_information) points out that CpuRate must not be 0, and for ControlFlags:
> The scheduling policy for CPU rate control. This member can be one of the following values.
> _(continues to list flag values; 0 is not in the list)_

However judging by a second repro, this issue only manifests if CPU limits have not been set before. If they have, the following code seems to works to disable the previous limits:

```csharp
using (var jobObject = new JobObject())
{
    var firstLimits = new JobLimits();
    firstLimits.CpuRate = new CpuRateLimit(20, false);
    jobObject.SetLimits(firstLimits);

    var jobLimits = new JobLimits();
    jobLimits.Options = JobOptions.TerminateProcessesWhenJobClosed;
    jobLimits.ActiveProcesses = 1;
    jobObject.SetLimits(jobLimits);
}
```

Fix:

CPU limits should only be set if they contain any values, or if they are currently enabled and should be disabled. Pseudo-code:
```csharp
if (newCpuLimits.ControlFlags != 0 || currentCpuLimits.ControlFlags != 0)
    SetInformationJobObject(...);
```

**Comment by williamb1024** [comment]
Thanks for the detailed description. I've corrected the issue using your suggested solution. I've posted an updated package on nuget.org, which should be available soon.

**Comment by m-mertz** [comment]
Thanks William!
