### ISSUE TITLE
Signed version?

### ISSUE THREAD

**Issue by tgeng** [williamb1024/fs-processes#6]
First thank you so much for writing this nice bridge library! It's very easy to use!

However our project needs to be signed so could you publish a signed version of this?

Thank you!

**Comment by williamb1024** [comment]
Do you mean strong named or actually authenticode signed?

**Comment by tgeng** [comment]
Thanks! I mean strong named assembly.

**Comment by williamb1024** [comment]
I'll look into publishing a strong named assembly, but I won't be able to get to it until after the end of the year.

**Comment by williamb1024** [comment]
Added signing key and updated the nuget package.

See 8fb3cfcf82f805547b29590e6296ae87ab15e585
